config/routes.rb
Rails.application.routes.draw do
  get 'checkout/start'

  get 'checkout/receipt'

  get 'carts/view'

  get 'sign_in' => 'session#new', as: :sign_in
  post 'sign_in' => 'session#create'
  get 'sign_out' => 'session#delete', as: :sign_out

  get 'sign_up' => 'user#new', as: :new_user
  post 'sign_up' => 'user#create', as: :users

  root 'books#index'
  resources :books

  resources :authors

  namespace :api do
    resources :books
    resources :authors
  end

  get 'cart' => 'carts#view', as: :cart
  post 'cart' => 'carts#add_to_cart', as: :add_to_cart
  delete 'cart' => 'carts#remove_from_cart', as: :remove_from_cart
  post 'checkout' => 'carts#process_payment', as: :process_payment
  get 'receipt/:id' => 'carts#receipt', as: :receipt

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books, dependent: :destroy
  validates :first_name, :last_name, :bio, presence: true

  attachment :photo

  def full_name
    [first_name, last_name].join(" ")
  end

end

app/controllers/api/authors_controller.rb
class Api::AuthorsController < ApplicationController
  require 'open-uri'

  def index
    @authors = Author.all.order("last_name asc")
  end

  def show
    @author = Author.find_by id: params[:id]
  end

  def create
    @author = Author.new author_params

    url = params[:author][:photo_url]
    if url.present?
      open(url, "rb") do |file|
        @author.photo = file
      end
    end

    if @author.save
      render :index
    else
      render json: {errors: @author.errors}, status: 422
    end
  end

  def update
    @author = Author.find_by id: params[:id]

    url = params[:author][:photo_url]
    if url.present?
      open(url, "rb") do |file|
        @author.photo = file
      end
    end

    if @author.update author_params
      render :show
    else
      render json: {errors: @author.errors}, status: 422
    end
  end

  def destroy
    @author = Author.find_by id: params[:id]
    @author.destroy
    head :ok
  end

  def author_params
    params.require(:author).permit(:first_name, :last_name, :bio, :photo)
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action do
    @current_user = User.find_by id: session[:user_id]
    if @current_user.blank?
      store_location
      redirect_to sign_in_path
    end
  end

  def index
    @authors = Author.all.order("last_name asc")
  end

  def show
    @author = Author.find_by id: params[:id]
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new author_params

    if @author.save
      redirect_to authors_path
    else
      render :new
    end
  end

  def edit
    @author = Author.find_by id: params[:id]
  end

  def update
    @author = Author.find_by id: params[:id]

    if @author.update author_params
      redirect_to author_path
    else
      render :edit
    end
  end

  def destroy
    @author = Author.find_by id: params[:id]
    @author.destroy
    redirect_to authors_path
  end

  def author_params
    params.require(:author).permit(:first_name, :last_name, :bio, :photo)
  end
end

app/helpers/api/authors_helper.rb
module Api::AuthorsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<% if @author.errors.any? %>
  <%= pluralize(@author.errors.count, 'error') %> prevented your form from success.
  <ul class="mdl-list">
    <% @author.errors.full_messages.each do |msg| %>
      <li class="mdl-list__item"><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @author do |f| %>

<div class="mdl-textfield mdl-js-textfield">
  <%= f.text_field :first_name, class: "mdl-textfield__input" %>
  <% if @author.errors[:first_name].any? %>
    <span class="error-text">* <%= @author.errors[:name].join(", ") %> </span>
  <% end %>
  <%= f.label :first_name, class: "mdl-textfield__label" %>
</div>

<div class="mdl-textfield mdl-js-textfield">
  <%= f.text_field :last_name, class: "mdl-textfield__input" %>
  <% if @author.errors[:last_name].any? %>
    <span class="error-text">* <%= @author.errors[:name].join(", ") %> </span>
  <% end %>
  <%= f.label :last_name, class: "mdl-textfield__label" %>
</div>

<div class="mdl-textfield mdl-js-textfield">
  <%= f.text_area :bio, class: "mdl-textfield__input" %>
  <% if @author.errors[:bio].any? %>
    <span class="error-text">* <%= @author.errors[:name].join(", ") %> </span>
  <% end %>
  <%= f.label :bio, class: "mdl-textfield__label" %>
</div>

<div class="">
  <%= f.label :photo, {class: "mdl-selectfield__select", style: "color: #BDBDBD;"}%>
  <%= f.attachment_field :photo, class: "" %>
  <% if @author.errors[:photo].any? %>
    <span class="mdl-textfield__error">* <%= @author.errors[:photo].join(", ") %> </span>
  <% end %>
</div>

<br>
<div>
  <%= f.submit class: "mdl-button mdl-js-button mdl-button--raised mdl-button--colored" %>
</div>

<% end %>

app/views/authors/edit.html.erb
<div class="demo-container mdl-grid">
  <div class="mdl-cell mdl-cell--2-col mdl-cell--hide-tablet mdl-cell--hide-phone"></div>
  <div class="demo-content mdl-color--white mdl-shadow--4dp content mdl-color-text--grey-800 mdl-cell mdl-cell--8-col">
      <h4>
        <div class="delete-button">
          <%= link_to author_path(id: @author.id), class: "mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored", method: :delete, data: {confirm: "Are you sure you want to delete?"} do %>
            <i class="material-icons">delete</i>
          <% end %>
          Edit Author
        </div>
      </h4>

      <%= render 'form' %>
  </div>

</div>

app/views/authors/index.html.erb
<div class="index">

  <div class="" style="padding-left: 20px;">
    <%= link_to authors_path, class: "mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect" do %>
      <i class="material-icons">refresh</i>
    <% end %>
  </div>

  <div class="item-list">
    <div class="mdl-grid">
      <% @authors.each do |author| %>

        <div class="mdl-cell mdl-cell--4-col mdl-cell--6-col-tablet">
          <div class="demo-card-square mdl-card mdl-shadow--2dp">
            <div class="mdl-card__title mdl-card--expand" style="background: url(<%= author.photo_url %>); background-position: top; background-size: 100%; background-repeat: no-repeat; min-width: 100%;">
              <div class="go-to-button">
                <%= link_to author_path(id: author.id), class: "mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect" do %>
                  <i class="material-icons">call_made</i>
                <% end %>
              </div>
            </div>
            <div class="mdl-card__supporting-text">
              <%= link_to author.bio.truncate(150), author_path(id: author.id), style: "text-decoration: none; color: #212121;"%>
            </div>
            <div class="mdl-card__actions mdl-card--border">
              <small style="padding-left: 10px;">
                <%= %>
              </small>
              <%= link_to author.full_name, author_path(id: author.id), class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" %>
            </div>
          </div>
        </div>
      <% end %>

    </div>
  </div>

</div>

app/views/authors/new.html.erb
<div class="demo-container mdl-grid">
  <div class="mdl-cell mdl-cell--2-col mdl-cell--hide-tablet mdl-cell--hide-phone"></div>
  <div class="demo-content mdl-color--white mdl-shadow--4dp content mdl-color-text--grey-800 mdl-cell mdl-cell--8-col">
      <h4>Add Author</h4>

      <%= render 'form' %>
  </div>

</div>

app/views/authors/show.html.erb
<div class="show">
  <div class="demo-card mdl-grid">
    <div class="demo-content mdl-color--white mdl-shadow--4dp content mdl-color-text--grey-800 mdl-cell mdl-cell--6-col">
      <h4>
        <%= link_to edit_author_path(id: @author.id), class: "mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored" do %>
          <i class="material-icons">edit</i>
        <% end %>
        <%= @author.full_name %>
      </h4>

      <div class="photo">
        <%= image_tag @author.photo_url %>
      </div>

    </div>
    <div class="demo-content mdl-color--white mdl-shadow--4dp content mdl-color-text--grey-800 mdl-cell mdl-cell--6-col">
      <p><%= @author.bio %></p>
      <p class="" style="text-decoration: underline;"><br>Works</p>
      <ul>
        <% @author.books.each do |book| %>
          <li><%= link_to book.title, book_path(id: book.id), style:"text-decoration: none; color: #424242;" %><small> (<%= number_to_currency(book.price) %>)</small></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>