config/routes.rb
Rails.application.routes.draw do
  get 'checkout/start'

  get 'checkout/receipt'

  get 'carts/view'

  get 'sign_in' => 'session#new', as: :sign_in
  post 'sign_in' => 'session#create'
  get 'sign_out' => 'session#delete', as: :sign_out

  get 'sign_up' => 'user#new', as: :new_user
  post 'sign_up' => 'user#create', as: :users

  root 'books#index'
  resources :books

  resources :authors

  namespace :api do
    resources :books
    resources :authors
  end

  get 'cart' => 'carts#view', as: :cart
  post 'cart' => 'carts#add_to_cart', as: :add_to_cart
  delete 'cart' => 'carts#remove_from_cart', as: :remove_from_cart
  post 'checkout' => 'carts#process_payment', as: :process_payment
  get 'receipt/:id' => 'carts#receipt', as: :receipt

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author
  has_many :order_items

  validates :title, :price, :author_id, presence: true
  validates_numericality_of :price, :greater_than => 0, :less_than => 1000
  validates_format_of :price, :with => /\A\d+(?:\.\d{0,2})?\z/

  attachment :photo

end

app/controllers/api/books_controller.rb
class Api::BooksController < ApplicationController
  require 'open-uri'

  def index
    @books = Book.all.order("title asc")
  end

  def show
    @book = Book.find_by id: params[:id]
  end

  def create
    @book = Book.new book_params

    url = params[:book][:photo_url]
    if url.present?
      open(url, "rb") do |file|
        @book.photo = file
      end
    end

    if @book.save
      render :index
    else
      render json: {errors: @book.errors}, status: 422
    end
  end

  def update
    @book = Book.find_by id: params[:id]

    url = params[:book][:photo_url]
    if url.present?
      open(url, "rb") do |file|
        @book.photo = file
      end
    end

    if @book.update book_params
      render :show
    else
      render json: {errors: @book.errors}, status: 422
    end
  end

  def destroy
    @book = Book.find_by id: params[:id]
    @book.destroy
    head :ok
  end

  def authors
    @authors = Author.all.order("last_name asc")
  end

  def book_params
    params.require(:book).permit(:title, :photo, :price, :author_id)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action except: [:index] do
    @current_user = User.find_by id: session[:user_id]
    if @current_user.blank?
      store_location
      redirect_to sign_in_path
    end
  end

  def index
    @books = Book.all.order("title asc")
  end

  def show
    @book = Book.find_by id: params[:id]
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new book_params

    if @book.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @book = Book.find_by id: params[:id]
  end

  def update
    @book = Book.find_by id: params[:id]

    if @book.update book_params
      redirect_to book_path(id: @book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find_by id: params[:id]
    @book.destroy
    redirect_to root_path
  end

  def book_params
    params.require(:book).permit(:title, :photo, :price, :author_id)
  end
end

app/helpers/api/books_helper.rb
module Api::BooksHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<% if @book.errors.any? %>
  <%= pluralize(@book.errors.count, 'error') %> prevented your form from success.
  <ul class="mdl-list">
    <% @book.errors.full_messages.each do |msg| %>
      <li class="mdl-list__item"><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @book do |f| %>

<div class="mdl-textfield mdl-js-textfield">
  <%= f.text_field :title, class: "mdl-textfield__input" %>
  <% if @book.errors[:title].any? %>
    <span class="error-text">* <%= @book.errors[:name].join(", ") %> </span>
  <% end %>
  <%= f.label :title, class: "mdl-textfield__label" %>
</div>

<div class="mdl-textfield mdl-js-textfield">
  <%= f.text_field :price, class: "mdl-textfield__input" %>
  <% if @book.errors[:price].any? %>
    <span class="error-text">* <%= @book.errors[:name].join(", ") %> </span>
  <% end %>
  <%= f.label :price, class: "mdl-textfield__label" %>
</div>

<div class="">
  <%= f.label :photo, {class: "mdl-selectfield__select", style: "color: #BDBDBD;"}%>
  <%= f.attachment_field :photo, class: "" %>
  <% if @book.errors[:photo].any? %>
    <span class="mdl-textfield__error">* <%= @book.errors[:photo].join(", ") %> </span>
  <% end %>
</div>

<div class="mdl-textfield mdl-js-textfield">
  <%= f.label :author_id, {class: "mdl-selectfield__select", style: "color: #BDBDBD;"} %>
  <%= f.collection_select :author_id, Author.all.order("last_name asc"), :id, :full_name, {prompt: true}, {class: "option"}%>
</div>

<div>
  <%= f.submit class: "mdl-button mdl-js-button mdl-button--raised mdl-button--colored" %>
</div>

<% end %>

app/views/books/edit.html.erb
<div class="demo-container mdl-grid">
  <div class="mdl-cell mdl-cell--2-col mdl-cell--hide-tablet mdl-cell--hide-phone"></div>
  <div class="demo-content mdl-color--white mdl-shadow--4dp content mdl-color-text--grey-800 mdl-cell mdl-cell--8-col">
      <h4>
        <div class="delete-button">
          <%= link_to book_path(id: @book.id), class: "mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored", method: :delete, data: {confirm: "Are you sure you want to delete?"} do %>
            <i class="material-icons">delete</i>
          <% end %>
          Edit Book
        </div>
      </h4>

      <%= render 'form' %>
  </div>

</div>

app/views/books/index.html.erb
<div class="index">
  <%= react_component('BookList') %>
</div>

app/views/books/new.html.erb
<div class="demo-container mdl-grid">
  <div class="mdl-cell mdl-cell--2-col mdl-cell--hide-tablet mdl-cell--hide-phone"></div>
  <div class="demo-content mdl-color--white mdl-shadow--4dp content mdl-color-text--grey-800 mdl-cell mdl-cell--8-col">
      <h4>Add Book</h4>

      <%= render 'form' %>
  </div>

</div>

app/views/books/show.html.erb
<div class="show">
  <div class="demo-card mdl-grid">
    <div class="demo-content mdl-color--white mdl-shadow--4dp content mdl-color-text--grey-800 mdl-cell mdl-cell--6-col">
      <h4>
        <%= link_to edit_book_path(id: @book.id), class: "mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored" do %>
          <i class="material-icons">edit</i>
        <% end %>
        <%= @book.title %>
      </h4>
      <div class="photo">
        <%= image_tag @book.photo_url %>
      </div>
      <div class="price">
        <h4>
          <%= number_to_currency(@book.price) %>
        </h4>
        <% if @book.inventory == 0 %>
          <h4><small>OUT OF STOCK</small></h4>
        <% else %>
          <% if @book.inventory == 1 %>
            <h4><small>Hurry! Only 1 left in stock.</small></h4>
          <% end %>
          <%= link_to 'Add to Cart', add_to_cart_path(book_id: @book.id), class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect', method: :post %>
        <% end %>
      </div>
    </div>
    <div class="demo-content mdl-color--white mdl-shadow--4dp content mdl-color-text--grey-800 mdl-cell mdl-cell--6-col">
      <h4><%= link_to @book.author.full_name, author_path(id: @book.author_id) %></h4>
      <p><%= @book.author.bio %></p>
    </div>
  </div>
</div>