config/routes.rb
Rails.application.routes.draw do
  get 'checkout/start'

  get 'checkout/receipt'

  get 'carts/view'

  get 'sign_in' => 'session#new', as: :sign_in
  post 'sign_in' => 'session#create'
  get 'sign_out' => 'session#delete', as: :sign_out

  get 'sign_up' => 'user#new', as: :new_user
  post 'sign_up' => 'user#create', as: :users

  root 'books#index'
  resources :books

  resources :authors

  namespace :api do
    resources :books
    resources :authors
  end

  get 'cart' => 'carts#view', as: :cart
  post 'cart' => 'carts#add_to_cart', as: :add_to_cart
  delete 'cart' => 'carts#remove_from_cart', as: :remove_from_cart
  post 'checkout' => 'carts#process_payment', as: :process_payment
  get 'receipt/:id' => 'carts#receipt', as: :receipt

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def view
    @order = Order.find_by status: 'cart', user_id: @current_user.id
  end

  def add_to_cart
    @book = Book.find_by id: params[:book_id]

    order = Order.find_by status: 'cart', user_id: @current_user.id
    if order.nil?
      order = Order.new
      order.user = @current_user
      order.purchased_at = Time.now
      order.save!
    end

    order_item = OrderItem.find_by order_id: order.id, book_id: @book.id
    if order_item.present?
      order_item.quantity += 1
    else
      order_item = OrderItem.new
      order_item.order = order
      order_item.book = @book
      order_item.price = @book.price
      order_item.shipping_cost = @book.shipping_cost
      order_item.quantity = 1
    end

    if order_item.quantity <= @book.inventory
      @book.inventory -= order_item.quantity
      @book.save
      order_item.save!
    end

    redirect_to cart_path
  end

  def remove_from_cart
    @order = Order.find_by status: 'cart', user_id: @current_user.id
    @book = Book.find_by id: params[:book_id]
    order_item = OrderItem.find_by order_id: @order.id, book_id: @book.id
    @book.inventory += order_item.quantity
    @book.save
    order_item.destroy
    redirect_to cart_path
  end

  def process_payment
    @order = Order.find_by status: 'cart', user_id: @current_user.id

    card_token = params[:stripeToken]

    Stripe.api_key = "sk_test_wHzmUvlgjN7NWOsoIRsR2sJT"

    Stripe::Charge.create(
      :amount => @order.total_price_in_cents,
      :currency => "usd",
      :source => card_token,
      :description => @order.description
    )

    @order.update status: 'pending'

    redirect_to receipt_path(id: @order.id)
  end

  def receipt
    @order = Order.find_by id: params[:id]

    ReceiptMailer.send_receipt(@order, @current_user).deliver_now
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/receipt.html.erb
<div class="cart">
  <div class="demo-container mdl-grid">
    <div class="mdl-cell mdl-cell--2-col mdl-cell--hide-tablet mdl-cell--hide-phone"></div>
    <div class="demo-content mdl-color--white mdl-shadow--4dp content mdl-color-text--grey-800 mdl-cell mdl-cell--8-col">
      <h3>Thank you for your order!</h3>
      <% if @order %>
        <h3><small><%=@order.description %></small></h3>
        <% @order.order_items.each do |order_item| %>
          <hr>
          <div class="order-item">
            <div><%= image_tag attachment_url(order_item.book, :photo, :fill, 100, 150, format: "jpg") %></div>
            <ul>
              <li>Title: <%= order_item.book.title %></li>
              <li>Quantity: <%= order_item.quantity %></li>
              <li>Total Price: <%= number_to_currency order_item.total_price %></li>
            </ul>
          </div>
        <% end %>
        <hr>
        <h5 style="text-align: right;">Order Total: <%= number_to_currency @order.total_price %></h5>
        <div class="checkout">
            <%= link_to 'Return to Books', root_path, class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/carts/view.html.erb
<div class="cart">
  <div class="demo-container mdl-grid">
    <div class="mdl-cell mdl-cell--2-col mdl-cell--hide-tablet mdl-cell--hide-phone"></div>
    <div class="demo-content mdl-color--white mdl-shadow--4dp content mdl-color-text--grey-800 mdl-cell mdl-cell--8-col">
      <h3><%= @current_user.name %>'s cart</h3>
      <% if @order %>
        <% @order.order_items.each do |order_item| %>
          <hr>
          <div class="order-item">
            <div><%= image_tag attachment_url(order_item.book, :photo, :fill, 100, 150, format: "jpg") %></div>
            <ul>
              <li>Title: <%= order_item.book.title %></li>
              <li>Quantity: <%= order_item.quantity %></li>
              <li>Total Price: <%= number_to_currency order_item.total_price %></li>
            </ul>
            <div class="order-img-btn">
              <%= link_to 'Remove from Cart', remove_from_cart_path(book_id: order_item.book_id), class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect', method: :delete %>
            </div>
          </div>
        <% end %>
        <hr>
        <h5 style="text-align: right;">Order Total: <%= number_to_currency @order.total_price %></h5>
        <div class="checkout">
          <% if @order.order_items.present? %>
            <%= form_tag process_payment_path, method: :post, id: "payment-form" do %>

              <script
                src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="pk_test_5JVSPhieKsIPIFTadSnKl3vs"
                data-name="The Iron Library"
                data-description="<%= @order.description %>"
                data-amount="<%= @order.total_price_in_cents %>"
                data-email="<%= @current_user.email %>"
                data-shipping-address="true"
                data-locale="auto">
              </script>

          <% end %>
          <% else %>
            <%= link_to 'Keep Shopping', root_path, class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent' %>
          <% end %>
        </div>
        <% else %>
        <%= link_to 'Keep Shopping', root_path, class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent' %>
      <% end %>
    </div>
  </div>
</div>