config/routes.rb
Rails.application.routes.draw do
  get 'checkout/start'

  get 'checkout/receipt'

  get 'carts/view'

  get 'sign_in' => 'session#new', as: :sign_in
  post 'sign_in' => 'session#create'
  get 'sign_out' => 'session#delete', as: :sign_out

  get 'sign_up' => 'user#new', as: :new_user
  post 'sign_up' => 'user#create', as: :users

  root 'books#index'
  resources :books

  resources :authors

  namespace :api do
    resources :books
    resources :authors
  end

  get 'cart' => 'carts#view', as: :cart
  post 'cart' => 'carts#add_to_cart', as: :add_to_cart
  delete 'cart' => 'carts#remove_from_cart', as: :remove_from_cart
  post 'checkout' => 'carts#process_payment', as: :process_payment
  get 'receipt/:id' => 'carts#receipt', as: :receipt

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books, dependent: :destroy
  validates :first_name, :last_name, :bio, presence: true

  attachment :photo

  def full_name
    [first_name, last_name].join(" ")
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author
  has_many :order_items

  validates :title, :price, :author_id, presence: true
  validates_numericality_of :price, :greater_than => 0, :less_than => 1000
  validates_format_of :price, :with => /\A\d+(?:\.\d{0,2})?\z/

  attachment :photo

end

app/models/mechanize.rb
require 'rubygems'
require 'mechanize'

agent = Mechanize.new

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :order_items
  has_many :books, through: :order_items

  def description
    "Order ##{id}: #{order_items.map{|order_item| order_item.book.title}.join(', ')}"
  end

  def total_price
    order_items.map{|order_item| order_item.total_price}.sum
  end

  def total_price_in_cents
    (total_price * 100).to_i
  end

end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :book
  belongs_to :order

  def total_price
    quantity * price
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, :email, presence: true
  validates :name, :email, uniqueness: true

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session


  before_action do
    @current_user = User.find_by id: session[:user_id]
  end

  def store_location
    session[:return_to] = request.fullpath if request.get? && controller_name != "user" && controller_name != "session"
  end

  def redirect_back_or_default(default)
    redirect_to(session[:return_to] || default)
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action do
    @current_user = User.find_by id: session[:user_id]
    if @current_user.blank?
      store_location
      redirect_to sign_in_path
    end
  end

  def index
    @authors = Author.all.order("last_name asc")
  end

  def show
    @author = Author.find_by id: params[:id]
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new author_params

    if @author.save
      redirect_to authors_path
    else
      render :new
    end
  end

  def edit
    @author = Author.find_by id: params[:id]
  end

  def update
    @author = Author.find_by id: params[:id]

    if @author.update author_params
      redirect_to author_path
    else
      render :edit
    end
  end

  def destroy
    @author = Author.find_by id: params[:id]
    @author.destroy
    redirect_to authors_path
  end

  def author_params
    params.require(:author).permit(:first_name, :last_name, :bio, :photo)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action except: [:index] do
    @current_user = User.find_by id: session[:user_id]
    if @current_user.blank?
      store_location
      redirect_to sign_in_path
    end
  end

  def index
    @books = Book.all.order("title asc")
  end

  def show
    @book = Book.find_by id: params[:id]
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new book_params

    if @book.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @book = Book.find_by id: params[:id]
  end

  def update
    @book = Book.find_by id: params[:id]

    if @book.update book_params
      redirect_to book_path(id: @book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find_by id: params[:id]
    @book.destroy
    redirect_to root_path
  end

  def book_params
    params.require(:book).permit(:title, :photo, :price, :author_id)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def view
    @order = Order.find_by status: 'cart', user_id: @current_user.id
  end

  def add_to_cart
    @book = Book.find_by id: params[:book_id]

    order = Order.find_by status: 'cart', user_id: @current_user.id
    if order.nil?
      order = Order.new
      order.user = @current_user
      order.purchased_at = Time.now
      order.save!
    end

    order_item = OrderItem.find_by order_id: order.id, book_id: @book.id
    if order_item.present?
      order_item.quantity += 1
    else
      order_item = OrderItem.new
      order_item.order = order
      order_item.book = @book
      order_item.price = @book.price
      order_item.shipping_cost = @book.shipping_cost
      order_item.quantity = 1
    end

    if order_item.quantity <= @book.inventory
      @book.inventory -= order_item.quantity
      @book.save
      order_item.save!
    end

    redirect_to cart_path
  end

  def remove_from_cart
    @order = Order.find_by status: 'cart', user_id: @current_user.id
    @book = Book.find_by id: params[:book_id]
    order_item = OrderItem.find_by order_id: @order.id, book_id: @book.id
    @book.inventory += order_item.quantity
    @book.save
    order_item.destroy
    redirect_to cart_path
  end

  def process_payment
    @order = Order.find_by status: 'cart', user_id: @current_user.id

    card_token = params[:stripeToken]

    Stripe.api_key = "sk_test_wHzmUvlgjN7NWOsoIRsR2sJT"

    Stripe::Charge.create(
      :amount => @order.total_price_in_cents,
      :currency => "usd",
      :source => card_token,
      :description => @order.description
    )

    @order.update status: 'pending'

    redirect_to receipt_path(id: @order.id)
  end

  def receipt
    @order = Order.find_by id: params[:id]

    ReceiptMailer.send_receipt(@order, @current_user).deliver_now
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    email = params[:email]
    password =  params[:password]
    @user = User.find_by email: email
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      redirect_back_or_default root_path
    else
      render :new
    end
  end

  def delete
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.name = params[:user][:name]
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]

    if @user.save
      session[:user_id] = @user.id
      redirect_back_or_default root_path
    else
      render :new
    end
  end
end

app/helpers/api/authors_helper.rb
module Api::AuthorsHelper
end

app/helpers/api/books_helper.rb
module Api::BooksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Iron Library</title>
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <link rel="stylesheet" href="https://code.getmdl.io/1.1.1/material.indigo-pink.min.css">
  <script defer src="https://code.getmdl.io/1.1.1/material.min.js"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>

  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  <script type="text/javascript" src=" https://checkout.stripe.com/checkout.js"></script>



  <script type="text/javascript">
    Stripe.setPublishableKey('pk_test_5JVSPhieKsIPIFTadSnKl3vs');
  </script>

</head>
<body>

  <div class="mdl-layout__container has-scrolling-header">
    <div class="demo-layout mdl-layout mdl-layout--fixed-header mdl-js-layout mdl-color--grey-100 is-upgraded">
      <header class="demo-header mdl-layout__header mdl-layout__header--scroll mdl-color--grey-100 mdl-color-text--grey-800">
        <div class="mdl-layout__header-row">
          <%= link_to new_book_path, class: "mdl-button mdl-js-button mdl-button--fab mdl-button--mini-fab mdl-button--colored" do %>
            <i class="material-icons">add</i>
          <% end %>
          &nbsp;&nbsp;&nbsp;
          <div class="mdl-layout-spacer"><%= link_to "Books", root_path %></div>
          <%= link_to new_author_path, class: "mdl-button mdl-js-button mdl-button--fab mdl-button--mini-fab mdl-button--colored" do %>
            <i class="material-icons">add</i>
          <% end %>
          &nbsp;&nbsp;&nbsp;
          <div class="mdl-layout-spacer"><%= link_to "Authors", authors_path %></div>
          <!-- <div data-upgraded=",MaterialTextfield" class="mdl-textfield mdl-js-textfield mdl-textfield--expandable is-upgraded">
            <label data-upgraded=",MaterialButton" class="mdl-button mdl-js-button mdl-button--icon" for="search">
              <i class="material-icons">search</i>
            </label>
            <div class="mdl-textfield__expandable-holder">
              <input class="mdl-textfield__input" id="search" type="text">
              <label class="mdl-textfield__label" for="search">Enter your query...</label>
            </div>
          </div> -->
          <% if @current_user %>
            <div class="user-name">
              Hello <%= @current_user.name %>!              
            </div>
          <% end %>
          &nbsp;
          <% if @current_user %>
            <%= link_to "Sign Out", sign_out_path %>
            &nbsp;&nbsp;&nbsp;
            <%= link_to cart_path do %>
              <div class="mdl-button mdl-js-button mdl-button--fab mdl-button--mini-fab mdl-button--colored">
                <i class="material-icons" style="font-size: 16px;">shopping_cart</i>
              </div>
            <% end %>
          <% else %>
            <%= link_to "Sign In", sign_in_path %>
          <% end %>
        </div>
      </header>

      <div class="demo-ribbon"></div>
      <main class="demo-main mdl-layout__content">
        <%= yield %>
      </main>
    </div>
  </div>

</body>
</html>